[build]
  publish = "build" # Caminho para a pasta de build (gerada pelo React)
  command = "yarn build" # Comando para construir o projeto usando Yarn

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
