[build]
  publish = "build" # Caminho para a pasta de build (gerada pelo React)
  command = "npm run build" # Comando para construir o projeto

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
